using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AIRelief.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AspNetRoles"" (
                    ""Id""               text NOT NULL,
                    ""Name""             character varying(256),
                    ""NormalizedName""   character varying(256),
                    ""ConcurrencyStamp"" text,
                    CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
                );
                CREATE TABLE IF NOT EXISTS ""AspNetUsers"" (
                    ""Id""                   text NOT NULL,
                    ""UserName""             character varying(256),
                    ""NormalizedUserName""   character varying(256),
                    ""Email""                character varying(256),
                    ""NormalizedEmail""      character varying(256),
                    ""EmailConfirmed""       boolean NOT NULL,
                    ""PasswordHash""         text,
                    ""SecurityStamp""        text,
                    ""ConcurrencyStamp""     text,
                    ""PhoneNumber""          text,
                    ""PhoneNumberConfirmed"" boolean NOT NULL,
                    ""TwoFactorEnabled""     boolean NOT NULL,
                    ""LockoutEnd""           timestamp with time zone,
                    ""LockoutEnabled""       boolean NOT NULL,
                    ""AccessFailedCount""    integer NOT NULL,
                    CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
                );
                CREATE TABLE IF NOT EXISTS ""Groups"" (
                    ""ID""                       integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PlanName""                 character varying(400),
                    ""Name""                     character varying(400) NOT NULL,
                    ""GroupImageUrl""            character varying(2000),
                    ""PrimaryThemeColor""        character varying(7),
                    ""SecondaryThemeColor""      character varying(7),
                    ""NumberOfUserLicenses""     integer NOT NULL,
                    ""ExpiryDays""               integer,
                    ""ExpiryDateTime""           timestamp with time zone,
                    ""QueryTimeToCompleteDays""  integer NOT NULL,
                    ""QueryFrequency""           integer NOT NULL,
                    ""QueryPassingGrade""        integer NOT NULL,
                    ""QueryQuestionsRandom""     boolean NOT NULL,
                    ""QueryQuestionsFocussed""   boolean NOT NULL,
                    ""CreatedDate""              timestamp with time zone NOT NULL,
                    ""LastModifiedDate""         timestamp with time zone,
                    CONSTRAINT ""PK_Groups"" PRIMARY KEY (""ID"")
                );
                CREATE TABLE IF NOT EXISTS ""Questions"" (
                    ""ID""               integer GENERATED BY DEFAULT AS IDENTITY,
                    ""QuestionText""     character varying(1000),
                    ""MainText""         character varying(1000) NOT NULL,
                    ""Image""            character varying(1000),
                    ""ExplanationText""  character varying(2000),
                    ""ExplanationImage"" character varying(300),
                    ""Option1""          character varying(500) NOT NULL,
                    ""Option2""          character varying(500) NOT NULL,
                    ""Option3""          character varying(500),
                    ""Option4""          character varying(500),
                    ""Option5""          character varying(500),
                    ""CorrectAnswer""    character varying(500) NOT NULL,
                    ""AttemptsShown""    integer,
                    ""AttemptsCorrect""  integer,
                    ""BestAnswersRaw""   text,
                    ""Category""         character varying(100),
                    CONSTRAINT ""PK_Questions"" PRIMARY KEY (""ID"")
                );
                CREATE TABLE IF NOT EXISTS ""AspNetRoleClaims"" (
                    ""Id""          integer GENERATED BY DEFAULT AS IDENTITY,
                    ""RoleId""      text NOT NULL,
                    ""ClaimType""   text,
                    ""ClaimValue""  text,
                    CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId""
                        FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS ""AspNetUserClaims"" (
                    ""Id""          integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId""      text NOT NULL,
                    ""ClaimType""   text,
                    ""ClaimValue""  text,
                    CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS ""AspNetUserLogins"" (
                    ""LoginProvider""       character varying(128) NOT NULL,
                    ""ProviderKey""         character varying(128) NOT NULL,
                    ""ProviderDisplayName"" text,
                    ""UserId""              text NOT NULL,
                    CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
                    CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS ""AspNetUserRoles"" (
                    ""UserId"" text NOT NULL,
                    ""RoleId"" text NOT NULL,
                    CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
                    CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId""
                        FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS ""AspNetUserTokens"" (
                    ""UserId""          text NOT NULL,
                    ""LoginProvider""   character varying(128) NOT NULL,
                    ""Name""            character varying(128) NOT NULL,
                    ""Value""           text,
                    CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
                    CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""ID""                              integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email""                           character varying(256) NOT NULL,
                    ""Name""                            character varying(400) NOT NULL,
                    ""AuthLevel""                       integer NOT NULL,
                    ""GroupId""                         integer,
                    ""ExpiryDate""                      timestamp with time zone,
                    ""CreatedDate""                     timestamp with time zone NOT NULL,
                    ""LastModifiedDate""                timestamp with time zone,
                    ""DatetimeOfLastQuestionAttempt""   timestamp with time zone,
                    ""QueryFrequency""                  integer,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""ID""),
                    CONSTRAINT ""FK_Users_Groups_GroupId""
                        FOREIGN KEY (""GroupId"") REFERENCES ""Groups"" (""ID"") ON DELETE SET NULL
                );
                CREATE TABLE IF NOT EXISTS ""UserStatistics"" (
                    ""ID""                                   integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId""                               integer NOT NULL,
                    ""LastUpdated""                          timestamp with time zone NOT NULL,
                    ""CognitiveReflectionAttempts""          integer NOT NULL,
                    ""CognitiveReflectionPassed""            integer NOT NULL,
                    ""CognitiveReflectionScore""             integer NOT NULL,
                    ""CognitiveReflectionWeightedAverage""   numeric NOT NULL,
                    ""ReadingComprehensionAttempts""         integer NOT NULL,
                    ""ReadingComprehensionPassed""           integer NOT NULL,
                    ""ReadingComprehensionScore""            integer NOT NULL,
                    ""ReadingComprehensionWeightedAverage""  numeric NOT NULL,
                    ""CausalReasoningAttempts""              integer NOT NULL,
                    ""CausalReasoningPassed""                integer NOT NULL,
                    ""CausalReasoningScore""                 integer NOT NULL,
                    ""CausalReasoningWeightedAverage""       numeric NOT NULL,
                    ""MetacognitionAttempts""                integer NOT NULL,
                    ""MetacognitionPassed""                  integer NOT NULL,
                    ""MetacognitionScore""                   integer NOT NULL,
                    ""MetacognitionWeightedAverage""         numeric NOT NULL,
                    ""ShortTermMemoryAttempts""              integer NOT NULL,
                    ""ShortTermMemoryPassed""                integer NOT NULL,
                    ""ShortTermMemoryScore""                 integer NOT NULL,
                    ""ShortTermMemoryWeightedAverage""       numeric NOT NULL,
                    ""ConfidenceCalibrationAttempts""        integer NOT NULL,
                    ""ConfidenceCalibrationPassed""          integer NOT NULL,
                    ""ConfidenceCalibrationScore""           integer NOT NULL,
                    ""ConfidenceCalibrationWeightedAverage"" numeric NOT NULL,
                    ""OverallWeightedAverage""               numeric NOT NULL,
                    CONSTRAINT ""PK_UserStatistics"" PRIMARY KEY (""ID""),
                    CONSTRAINT ""FK_UserStatistics_Users_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""ID"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_AspNetRoleClaims_RoleId""      ON ""AspNetRoleClaims"" (""RoleId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""RoleNameIndex""             ON ""AspNetRoles"" (""NormalizedName"") WHERE ""NormalizedName"" IS NOT NULL;
                CREATE INDEX IF NOT EXISTS ""IX_AspNetUserClaims_UserId""      ON ""AspNetUserClaims"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_AspNetUserLogins_UserId""      ON ""AspNetUserLogins"" (""UserId"");
                CREATE INDEX IF NOT EXISTS ""IX_AspNetUserRoles_RoleId""       ON ""AspNetUserRoles"" (""RoleId"");
                CREATE INDEX IF NOT EXISTS ""EmailIndex""                      ON ""AspNetUsers"" (""NormalizedEmail"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""UserNameIndex""             ON ""AspNetUsers"" (""NormalizedUserName"") WHERE ""NormalizedUserName"" IS NOT NULL;
                CREATE INDEX IF NOT EXISTS ""IX_Users_GroupId""                ON ""Users"" (""GroupId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserStatistics_UserId""  ON ""UserStatistics"" (""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "AspNetRoleClaims");
            migrationBuilder.DropTable(name: "AspNetUserClaims");
            migrationBuilder.DropTable(name: "AspNetUserLogins");
            migrationBuilder.DropTable(name: "AspNetUserRoles");
            migrationBuilder.DropTable(name: "AspNetUserTokens");
            migrationBuilder.DropTable(name: "Questions");
            migrationBuilder.DropTable(name: "UserStatistics");
            migrationBuilder.DropTable(name: "AspNetRoles");
            migrationBuilder.DropTable(name: "AspNetUsers");
            migrationBuilder.DropTable(name: "Users");
            migrationBuilder.DropTable(name: "Groups");
        }
    }
}
