using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AIRelief.Migrations
{
    /// <inheritdoc />
    public partial class AddUserQuestions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""UserQuestions"" (
                    ""ID""                   integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserID""               integer NOT NULL,
                    ""QuestionID""           integer NOT NULL,
                    ""DateFirstAttempted""   timestamp with time zone NOT NULL,
                    ""DateLastAttempted""    timestamp with time zone,
                    ""AnsweredCorrectly""    boolean NOT NULL,
                    CONSTRAINT ""PK_UserQuestions"" PRIMARY KEY (""ID""),
                    CONSTRAINT ""FK_UserQuestions_Questions_QuestionID""
                        FOREIGN KEY (""QuestionID"") REFERENCES ""Questions"" (""ID"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_UserQuestions_Users_UserID""
                        FOREIGN KEY (""UserID"") REFERENCES ""Users"" (""ID"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_UserQuestions_QuestionID"" ON ""UserQuestions"" (""QuestionID"");
                CREATE INDEX IF NOT EXISTS ""IX_UserQuestions_UserID""     ON ""UserQuestions"" (""UserID"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserQuestions");
        }
    }
}
