// <auto-generated />
using System;
using AIRelief.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIRelief.Migrations
{
    [DbContext(typeof(AIReliefContext))]
    [Migration("20260217235446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AIRelief.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfUserLicenses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanName")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryThemeColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryPassingGrade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QueryQuestionsFocussed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QueryQuestionsRandom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryTimeToCompleteDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryThemeColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AIRelief.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option5")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option6")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option7")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option8")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("backvalue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("correctionimage")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("correctiontext")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("heading")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("maintext")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("nextvalue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AIRelief.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIRelief.Models.UserStatistics", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CausalReasoningAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CausalReasoningPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CausalReasoningScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CausalReasoningWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<int>("CognitiveReflectionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CognitiveReflectionPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CognitiveReflectionScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CognitiveReflectionWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceCalibrationAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceCalibrationPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceCalibrationScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConfidenceCalibrationWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetacognitionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetacognitionPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetacognitionScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MetacognitionWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverallWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingComprehensionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingComprehensionPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingComprehensionScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReadingComprehensionWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShortTermMemoryAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortTermMemoryPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortTermMemoryScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShortTermMemoryWeightedAverage")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AIRelief.Models.User", b =>
                {
                    b.HasOne("AIRelief.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AIRelief.Models.UserStatistics", b =>
                {
                    b.HasOne("AIRelief.Models.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("AIRelief.Models.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIRelief.Models.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AIRelief.Models.User", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
